### ISSUE TITLE
Trans complied code is getting included in the code coverage

### ISSUE THREAD

**Issue by ohmirocks** [zordius/gulp-jsx-coverage#14]
Hi, 

I am using this NPM module to get the code coverage for my react component and it works great. But my code coverage seems to be really down because of all the transplied code. I read about isparta which will help in improving code is this something you can add it as part of this module itself?

Thanks
Om

**Comment by zordius** [comment]
It's may be possible, will evaluate this.

**Comment by zordius** [comment]
Now gulp-jsx-coverage supports isparta and new version released (0.3.0) , please check the document, thanks.
