### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by yormi** [zordius/gulp-jsx-coverage#17]
Caused by Istanbul.

> This error appeared in the transpiled code. Guys, are you using babel or something? Try to use fixed version from branch.
> 
> `npm install --save-dev gotwarlost/istanbul#source-map`

https://github.com/gotwarlost/istanbul/issues/429

**Comment by zordius** [comment]
Sorry, can you provide more information about this issue? I will close this issue first. You may reopen this if you think something should be resolved inside gulp-jsx-coverage.

**Comment by yormi** [comment]
Would it help if I give you the stacktrace ? The problem comes from the dependency istanbul but it's fixed on a separate branch. So I would suggest just to change gulp-jsx-coverage dependency for the `source-map` branch.

Or at least this issue may orient people who encounter that problem toward a solution :P

**Comment by zordius** [comment]
Good, I reopen this issue and keep this hint for other people (until the istanbul branch merged), thank you.

Another question, do you using isparta ? (it is a modified version of istanbul to handle sourceMap) Maybe you can resolve this issue by moving to this package.

**Comment by yormi** [comment]
You're welcome :)

I haven't try isparta yet since changing the dependency solved my problem. If I experience other troubles, that'll be the first thing I do.

**Comment by zordius** [comment]
When using new istanbul (0.3.8+) , this error happens. A newer version of gulp-jsx-coverage (0.3.2) released and should fix this issue, please try it, thanks.
