### ISSUE TITLE
.cjsx support

### ISSUE THREAD

**Issue by ragesoss** [zordius/gulp-jsx-coverage#19]
Would it be possible to add .cjsx support? My team is using cjsx for our main project, but we haven't yet figured out a way to get coverage for the .cjsx files.

**Comment by zordius** [comment]
Do you mean this? https://github.com/jsdf/coffee-react

I may do some code changes to support this.

**Comment by ragesoss** [comment]
Yes, that's the one. :-)

**Comment by zordius** [comment]
Now should supprt .cjsx well, please use the new version 0.3.6 and read the document for the new configs, thanks.
