### ISSUE TITLE
Include non-`require`d files in test coverage %

### ISSUE THREAD

**Issue by thenickcox** [zordius/gulp-jsx-coverage#21]
Istabul [appears to include untested files](https://github.com/gotwarlost/istanbul/issues/112) in the test coverage percentage, but `gulp-jsx-coverage` doesn't appear to. Is there a way to set an `includeUntested` flag in the config?

**Comment by zordius** [comment]
You can try to include all your target files into options.src then you can get coverage of not tested files. For example:

``` js
gulp.task('your_task_name', require('gulp-jsx-coverage').createTask({
    src: [
        // all test files
        'test/**/*.js',
        'test/components/*.jsx',
        // include all possible targets for whole picture of coverage
        'lib/*.js',
        'actions/*.js',
        'stores/*.js',
        'components/*.jsx',
    ],
    // other GJC options
    ....
}));
```
