### ISSUE TITLE
Support multiple threshold types

### ISSUE THREAD

**Issue by cliren** [zordius/gulp-jsx-coverage#25]
It would be nice to support multiple thresholds and fail tests if any of the fail first.
threshold: [
{
     type: 'functions', 
     min: 90
} ,
{
     type: 'lines', 
     min: 95
} 
]

**Comment by zordius** [comment]
Good feature, will work on it later, thank you for your suggestion!

**Comment by zordius** [comment]
new version 0.3.8 released for this, please try it, thanks.

**Comment by cliren** [comment]
Awesome, thanks!
