### ISSUE TITLE
Coverage difference between Linux and Mac

### ISSUE THREAD

**Issue by cliren** [zordius/gulp-jsx-coverage#27]
Has anyone seen the difference in coverage running on Linux vs Mac? @zordius Can you think of any specific settings we can apply to have a consistent experience as tests fail on continuous integration often due to this reason?

**Running on a Linux box:**

```
Statements   : 90.37% ( 3762/4163 )
Branches     : 82.48% ( 1257/1524 )
Functions    : 87.61% ( 863/985 )
Lines        : **92.99**% ( 3597/3868 )
```

Running on a mac box:

```
Statements   : 90.72% ( 3921/4322 )
Branches     : 82.48% ( 1257/1524 )
Functions    : 87.61% ( 863/985 )
Lines        : **93.27**% ( 3756/4027 )
```

**Comment by zordius** [comment]
not sure, the issue caused by line number, maybe I will check on all versions of installed npm packages.

**Comment by cliren** [comment]
Not seeing this anymore!

**Comment by zordius** [comment]
Good!
