### ISSUE TITLE
How to ignore coverage with istanbul ignore hints

### ISSUE THREAD

**Issue by cliren** [zordius/gulp-jsx-coverage#28]
/\* istanbul ignore next: untestable */

Adding the above ignore hint at the begging of a file doesn't seem to ignore coverage for a specific file (https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md). The only thing that seems to work using this gulp-jsx-coverage is the exclude option of istanbul as shown below. Has anyone seen this behavior ?

```
istanbul: {
      coverageVariable: "__MY_TEST_COVERAGE__",
      exclude: /node_modules|spec|yourfile|yourdirectory/
    }
```

**Comment by zordius** [comment]
`/* istanbul ignore next */` work on a `anything` and it only works for a file when the file only contains a function.

``` javascript

/* istanbul ignore next */
function a () {
   .....
}

// This still be covered....
function b () {
    ....
}
```

If you like to have file level ignore, use options.istanbul.exclude is a good idea.
