### ISSUE TITLE
100% coverage shown for jsx files with disabled tests

### ISSUE THREAD

**Issue by thetallweeks** [zordius/gulp-jsx-coverage#30]
I've been working on adding code coverage in this repo based off react-redux todomvc: https://github.com/thetallweeks/react-redux-es6-istanbul-starter-kit/tree/inaccurate-code-coverage

I set up gulp-jsx-coverage, but I'm seeing 100% coverage for all jsx files, even though the tests are currently disabled.

<img width="1422" alt="screen shot 2016-03-08 at 12 35 36 pm" src="https://cloud.githubusercontent.com/assets/1364726/13615470/51689aa0-e52a-11e5-9056-83d9ae3d9274.png">

<img width="1013" alt="screen shot 2016-03-08 at 12 25 09 pm" src="https://cloud.githubusercontent.com/assets/1364726/13615172/f3e6cf1a-e528-11e5-87aa-d35bf5b5a81a.png">

I've set up coverage in 2 ways:

```
"coverage": "babel-node ./node_modules/.bin/isparta cover _mocha",
"coverage-jsx": "gulp coverage"
```

Using babel-node ignores jsx files but gets more accurate coverage for non-jsx files:

**babel-node**
<img width="1409" alt="screen shot 2016-03-08 at 12 28 39 pm" src="https://cloud.githubusercontent.com/assets/1364726/13615297/81f6f366-e529-11e5-8fe1-91e4c9925956.png">

**gulp-jsx-coverage**
<img width="1407" alt="screen shot 2016-03-08 at 12 30 27 pm" src="https://cloud.githubusercontent.com/assets/1364726/13615318/9677fc0e-e529-11e5-9aa9-9848d2dd42e2.png">

Any help would be greatly appreciated.

**Relevant files:**
- [gulpfile.js](https://github.com/thetallweeks/react-redux-es6-istanbul-starter-kit/blob/inaccurate-code-coverage/gulpfile.js)
- [package.json](https://github.com/thetallweeks/react-redux-es6-istanbul-starter-kit/blob/inaccurate-code-coverage/package.json)
- [.babelrc](https://github.com/thetallweeks/react-redux-es6-istanbul-starter-kit/blob/inaccurate-code-coverage/.babelrc)
- [Footer.spec.js](https://github.com/thetallweeks/react-redux-es6-istanbul-starter-kit/blob/master/test/components/Footer.spec.js)

**Comment by zordius** [comment]
Thank you for the detail report! It's a known issue when `isparta` enabled, you can refer to #24 . We still waiting isparta or something upgraded to fix it. Now the only way to get better coverage report with `gulp-jsx-coverage` is disable isparta; you will get `transpiled` coverage with comment hints.

**Comment by thetallweeks** [comment]
Thank you for he response. I noticed that when `isparta` is disabled, I get some uncovered code:

<img width="1407" alt="screen shot 2016-03-10 at 10 43 51 am" src="https://cloud.githubusercontent.com/assets/1364726/13680384/2f6bde92-e6ad-11e5-8ed3-be8a320196f9.png">

I'm not sure exactly where this is coming from, but I believe the source code is well-tested. Have you come across anything like this before (with transpiled jsx)?

**Comment by zordius** [comment]
it is transpiled code from babel. You can prevent it to be applied to each files by enable `transform-runtime` plugin in your `.babelrc`:

```
{
    plugins: ['transform-es2015-template-literals', 'transform-runtime'],
    presets: ['react'],
    only: ['components/*.jsx'],
    sourceMap: 'both'
}
```

And then you can require `babel-runtime` once for your application then everything works.

**Comment by mhyrsal** [comment]
transform-runtime didn't make any difference. Still transpiling the code :( any update on this?

**Comment by zordius** [comment]
now new 0.4.0 released which is based on https://github.com/istanbuljs/babel-plugin-istanbul , please try it, thanks!
