### ISSUE TITLE
Running tests in parallel

### ISSUE THREAD

**Issue by cliren** [zordius/gulp-jsx-coverage#32]
Is it possible to add a feature to split tests and run them in parallel (by passing a config param or have a reducer to slice the sources into buckets of parallel tests) and collect coverage metrics at the end?

**Comment by zordius** [comment]
Mocha or most test framework are designed to run tests sequentially, the main reason is: when you testing you probably mocking something and you will restore the mocked function after the test case done. If the test cases run parallely, the mocked function will mess around.

Refer to: https://github.com/mochajs/mocha/issues/98
- A better way to run test cases safely is to execute test framework in different process. You can do something like this in gulp:

``` javascript
gulp.task('mocha_tests_in_process', function () {
    gulp.src('test/*.js')
    .pipe(start_sub_progress_to_run_a_test_file);
});
```

But you need more steps to collect coverage and test results.
- Another way to run test cases parallel is with https://github.com/danielstjules/mocha.parallel , you can try it. gulp-jsx-coverage can work with most test framework, you can check this example: https://github.com/zordius/gulp-jsx-coverage#usage-other-testing-frameworks

**Comment by cliren** [comment]
Thanks for your inputs, will try those. Another quick question, did you every try running a mocha spec runner in browser using coverage?

**Comment by zordius** [comment]
Well, no. I ever do browser testing with browserify + mocha but without coverage. But, if the code is without different path by environment, you should get same coverage numbers from either node or browser. (So, when I do browser tests I do not care coverage but only the test result)
