### ISSUE TITLE
No Sourcemaps on stack traces for failing tests

### ISSUE THREAD

**Issue by andrewzey** [zordius/gulp-jsx-coverage#4]
When tests are failing, the stack trace refers to the transpiled code, not the original source code, making it difficult to debug.

I'm looking into fixing this somehow with https://github.com/evanw/node-source-map-support

**Comment by zordius** [comment]
:+1:  Good point!

**Comment by tommyk** [comment]
+1, everything is on line 9 for me :\

**Comment by zordius** [comment]
https://github.com/zordius/gulp-jsx-coverage/releases/tag/v0.2.0 released and support this, please try it, thanks. And please read https://github.com/zordius/gulp-jsx-coverage#upgrade-notice
