### ISSUE TITLE
Make it optional to specify the `.jsx` (and `.coffee`) extension

### ISSUE THREAD

**Issue by pscanf** [zordius/gulp-jsx-coverage#7]
As the title says. Would it be doable at all or are there technical issues that prevent it?

**Comment by zordius** [comment]
We already provide option for this. The default transpiler option is only transpile .jsx files by babel and only handle .coffee files with coffee. And you can pass different regexp into `options.transpile.babel.include` or `options.transpile.coffee.include` to customize it. Please refer to README.md for more document, thanks.
