### ISSUE TITLE
Threshold settings

### ISSUE THREAD

**Issue by jameswlane** [zordius/gulp-jsx-coverage#8]
I am trying to figure out how to pass in a threshold setting to Istanbul to enforce 100% coverage.

**Comment by zordius** [comment]
Well, the question is about 'how to fail a gulp task with a coverage threshold' . So far I did not find any reporter for this under https://github.com/gotwarlost/istanbul/tree/master/lib/report , so I will create an new API for this.

**Comment by zordius** [comment]
new version 0.2.1 released and you can use `options.threshold` and `options.thresholdType` now, please read new document, thanks!

**Comment by jameswlane** [comment]
:+1:
