### ISSUE TITLE
Possible issue with proxyquire

### ISSUE THREAD

**Issue by Xantier** [zordius/gulp-jsx-coverage#9]
I noticed while bumping versions that my existing tests that are using proxyquire start failing on 0.2.x. On 0.1.3 all seem to go through fine and dandy. 

Note that these are not actually testing jsx/coffee files, am I using this plugin incorrectly?

Example: https://github.com/Xantier/nerd-stack/blob/master/spec/services/serverMediator.spec.js

**Comment by zordius** [comment]
Please read the https://github.com/zordius/gulp-jsx-coverage#upgrade-notice , the new version require mocha 2.2.2+ , update the depdency may help.

If the issue still there after you upgrade the mocha, please provide the error log,  thanks. :)

**Comment by zordius** [comment]
I saw the issue was fixed with proper config change and version upgrade https://travis-ci.org/Xantier/nerd-stack/builds/72342044 , so I close this issue, thanks.
